### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by liuzipeng** [KANIKIG/Multi-EasyGost#1]
希望能增加开机自启和在脚本中添加查看gost状态，感谢开发者

**Comment by KANIKIG** [comment]
您好，感谢您的反馈。
已经有开机自启功能了，重启机器转发并不会失效。
查看gost状态感觉没有必要，并没有遇到过启动失败的情况，如果您是要查看详细配置文件可以运行如下命令
`cat /etc/gost/config.json`
