### ISSUE TITLE
用人用过gost中转mtp吗，我怎么感觉我失败了

### ISSUE THREAD

**Issue by BlueSkyXN** [KANIKIG/Multi-EasyGost#10]
到底是支持还是不支持，mtptls的

**Comment by KANIKIG** [comment]
未测试过，但不通大概率为配置或服务自身问题，小概率为gost程序问题，可自行尝试。
此脚本只是简化操作gost配置文件的步骤，若为gost程序问题则无法解决。
不建议中转mtp，用socks套gost隧道能一样起到效果。

**Comment by BlueSkyXN** [comment]
> 未测试过，但不通大概率为配置或服务自身问题，小概率为gost程序问题，可自行尝试。
> 此脚本只是简化操作gost配置文件的步骤，若为gost程序问题则无法解决。
> 不建议中转mtp，用socks套gost隧道能一样起到效果。

哈哈，那我去试试socks5套隧道，谢谢了

**Comment by BlueSkyXN** [comment]
现在发现s5隧道和mtp隧道均可以，可能是之前操作错误

**Comment by vbigbang** [comment]
> 现在发现s5隧道和mtp隧道均可以，可能是之前操作错误

老哥你是怎么解决的 我也失败了
