### ISSUE TITLE
如何关闭udp加密

### ISSUE THREAD

**Issue by banxianl08** [KANIKIG/Multi-EasyGost#12]
有的国内中转机屏蔽了udp  用tls ws加密模式连接落地机，落地机没屏蔽udp 无法正常传输，延时非常大，各种测试后，只有两台机器均tcp+udp 开启状态下才能正常加密传输流量。一方udp被屏蔽 就无法加密传输流量。如何使用gost 不开启udp加密？

**Comment by KANIKIG** [comment]
自己用gost命令或者手动改配置文件，此脚本不提供相关支持。
