### ISSUE TITLE
关于GOST项目更新仓库的问题

### ISSUE THREAD

**Issue by LYCX2015** [KANIKIG/Multi-EasyGost#16]
作者，您好，GOST项目已更换新的仓库，版本为3.0，脚本可否同步更新下？
仓库地址为：https://github.com/go-gost/gost

**Comment by KANIKIG** [comment]
您好，我理解您焦急的心情。本人一直关注gost的开发进度，3.0几天前刚刚创建仓库，您应该能看到 WORK IN PROGRESS，还在开发中，得等正式版release。

**Comment by LYCX2015** [comment]
嗯嗯，好呢，谢谢您付出
