### ISSUE TITLE
config.json 文件替换后不生效

### ISSUE THREAD

**Issue by 110560** [KANIKIG/Multi-EasyGost#18]
/etc/gost 目录下的config.json 文件替换后不生效。。。
我想直接拖过去用的

**Comment by KANIKIG** [comment]
用脚本的重启功能默认会重写配置文件。
拖进去后不要用脚本重启，直接键入命令
`systemctl restart gost`
这个问题在下一版本将会改善，以适合不同需求的用户。

**Comment by 110560** [comment]
还没修改这个问题吗    
想把规则迁移到别的机器就好难呀

**Comment by KANIKIG** [comment]
不解决。你可以不用这个脚本，直接用命令。
