### ISSUE TITLE
如何看运行日志，我使用你的脚本只能用tcp+udp不加密模式，其他的模式连接不上。

### ISSUE THREAD

**Issue by banxianl08** [KANIKIG/Multi-EasyGost#2]
如何看运行日志，我使用你的脚本只能用tcp+udp不加密模式，其他的模式连接不上。

**Comment by banxianl08** [comment]
操作应该没问题，中转机加密  落地机解密，除了tcp不加密模式，其余的模式都联不通

**Comment by banxianl08** [comment]
操作应该没问题，中转机加密 落地机解密，除了tcp不加密模式，其余的模式都联不通  中转机端口测试也是开启状态，说明了端口已转发到落地机，流量加解密是有问题的

**Comment by banxianl08** [comment]
操作应该没问题，中转机加密 落地机解密，除了tcp不加密模式，其余的模式都联不通 中转机端口测试也是开启状态，说明了端口已转发到落地机，流量加解密是有问题的  
中转机配置: wss隧道   |65003  |35.xx.xx.xx:20212
落地机配置:wss解密   |20212  |122.xx.xx.xx:65003

**Comment by KANIKIG** [comment]
脚本实测并无问题，您可能遇到的问题：

- 端口映射关系错误，NAT机器内外网端口搞混

- 落地解密与中转对应错误，隧道落地机配置：接受流量端口应与中转对应，ip应填127.0.0.1，目标端口为v2或ss端口

- 机器本身问题

- 其他未知原因，可以找会用的人教学

**Comment by banxianl08** [comment]
谢谢
