### ISSUE TITLE
新建ss时，期望添加监听地址

### ISSUE THREAD

**Issue by MikoyChinese** [KANIKIG/Multi-EasyGost#28]
目前新建ss服务时，默认监听地址都是所有ip, 希望可以加入地址选项例如，127.0.0.1本地监听，其他服务也是类似。
第二目前，修改/etc/gost/config.json，在脚本重启，该文件会重新生成，无法手动修改。

**Comment by KANIKIG** [comment]
第一个可以用其他的ss程序，gost的ss性能并不优秀，可设置选项也较少。
第二个功能之前考虑过，对于小白脚本来说就不应该考虑自行修改配置文件的情况。自己写配置文件的话不使用此脚本，直接运行gost官方程序反而更方便。

**Comment by MikoyChinese** [comment]
好的，谢谢。
我想问问，如果我一台机器部署监听本地的ss, 然后在由本机进行gost加解密隧道，这样意义大么？就是加密和解密都是由本机进行。
