### ISSUE TITLE
用gost创建的ss节点，安卓机使用v2rayNG（版本v1.6.23）测试通但是无法打开网页

### ISSUE THREAD

**Issue by inpowerchiu** [KANIKIG/Multi-EasyGost#30]
用gost创建的ss节点，安卓机使用v2rayNG（版本v1.6.23）测试通但是无法打开网页，但是用shadowsocks app就能用，电脑和openwrt都可以，唯独v2rayNG不行。但是v2rayNG使用秋水逸冰docker搭建的ss却能正常使用，懵逼了。

**Comment by KANIKIG** [comment]
和gost ss支持的加密方式有关。推荐用秋水的ss，然后用gost对其加密。
