### ISSUE TITLE
你好，一键脚本安装后设置加密，出现错误提示，麻烦看下如何解决

### ISSUE THREAD

**Issue by soso1218** [KANIKIG/Multi-EasyGost#32]
awk: fatal: cannot open file `/etc/gost/rawconf' for reading (No such file or directory)
./gost.sh: line 769: ((: i <= : syntax error: operand expected (error token is "<= ")

**Comment by KANIKIG** [comment]
报错自己去查，开发者没有义务教你

**Comment by JoeZing** [comment]
> 报错自己去查，开发者没有义务教你

真搞笑，明显的脚本缺陷没有自动创建配置还理直气壮，开源了又如何
