### ISSUE TITLE
centos7系统安装完gost重启便会报错以下命令

### ISSUE THREAD

**Issue by 3262246353** [KANIKIG/Multi-EasyGost#33]
awk: fatal: cannot open file `/etc/gost/rawconf' for reading (没有那个文件或目录)
./gost.sh:行738: ((: i <= : 语法错误: 期待操作数 （错误符号是 "<= "）

**Comment by KANIKIG** [comment]
1. Centos7停止维护很久了，不建议再使用这个系统。
2. 这个问题与脚本无关

**Comment by Checkra2n** [comment]
> 1. Centos7停止维护很久了，不建议再使用这个系统。
> 2. 这个问题与脚本无关


./gost.sh: line 340: /etc/gost/rawconf: No such file or directory
./gost.sh: line 361: /etc/gost/config.json: No such file or directory
awk: fatal: cannot open file `/etc/gost/rawconf' for reading (No such file or directory)
./gost.sh: line 738: ((: i <= : syntax error: operand expected (error token is "<= ")
./gost.sh: line 370: /etc/gost/config.json: No such file or directory
Failed to restart gost.service: Unit gost.service not found.
配置已生效，当前配置如下
--------------------------------------------------------
                      GOST 配置                        
--------------------------------------------------------
序号|方法	    |本地端口	|目的地地址:目的地端口
--------------------------------------------------------
awk: fatal: cannot open file `/etc/gost/rawconf' for reading (No such file or directory)
./gost.sh: line 769: ((: i <= : syntax error: operand expected (error token is "<= ")

大佬 我用AZ的ubuntu也这样提示了 而且比这个多 ，是要换成20.04吗？
