### ISSUE TITLE
CDN功能(關於 ?host / ?ip 

### ISSUE THREAD

**Issue by willyboyshy** [KANIKIG/Multi-EasyGost#35]
https://v2.gost.run/port-forwarding/
根據內文提到
scheme://[bind_address]:port/[host]:hostport[,[host]:hostport]?ip=[host]:hostport][,[host]:hostport]]
確實頭痛，我看了好久

第六個選項的CDN有誤，腳本生成如下：
"tcp://:30000/{優選IP}:{連接端口}?host={cf_domain}"
但應該是：
"tcp://:30000/{優選IP}:{連接端口}?ip={cf_domain}:{連接端口}"

連接端口均為必填
是 ?ip 而非?host

(host個人認知是針對sni協議

---小白一個，煩請多多指教

**Comment by KANIKIG** [comment]
感谢反馈。这也说明此功能没什么人用过。

**Comment by willyboyshy** [comment]
應該不是沒人使用，而是因為這個錯誤不影響使用
根據多數人的理解，薅CDN時依舊會在v2ray客戶端填上Host，因此可以正常使用

此錯誤僅會引發安全性問題，任何人只要知道IP，端口，就可以任意填寫HOST域名偷你的流量

請問未來版本是否會修正呢?

**Comment by jameqq** [comment]
GOST总体架构已经趋于稳定，正式进入beta阶段，这个阶段主要是bug修复和文档完善 希望大佬更新3.0的脚本

**Comment by KANIKIG** [comment]
我也有持续关注更新情况，但是只能闲暇时间写，没法那么及时跟进，只能尽量了
