### ISSUE TITLE
因为博客无法评论所以来这里请教关于使用Gost隧道中转搭建Telegram代理的问题

### ISSUE THREAD

**Issue by gcphym** [KANIKIG/Multi-EasyGost#36]
看到了博主的这篇博文
https://blog.kanikig.xyz/%E7%9B%AE%E5%89%8D%E6%9C%80%E7%A8%B3%EF%BC%81%E4%BD%BF%E7%94%A8Gost%E9%9A%A7%E9%81%93%E4%B8%AD%E8%BD%AC%E6%90%AD%E5%BB%BATelegram%E4%BB%A3%E7%90%86/
请问一下按照文章里的说法，tg软件里面填写国内nat的ip和端口，国内nat和国外落地机之间是有加密隧道的，那从本地到国内nat呢？也是加密吗？会不会明文显示我在访问tg

**Comment by KANIKIG** [comment]
本地到nat是没加密的

**Comment by gcphym** [comment]
好的
