### ISSUE TITLE
Multi-EasyGost 支持Mtls吗？

### ISSUE THREAD

**Issue by sunteta** [KANIKIG/Multi-EasyGost#38]
由于搭建了 mtproto 代理。想用Multi-EasyGost 中转
但是用 TLS 模式一直不成功。

**Comment by KANIKIG** [comment]
不成功是你自己的原因，建议再检查下。mtls是复用，和你里面跑什么协议没关系，是由于实际使用效果不好，没有加到脚本里。

**Comment by sunteta** [comment]
所以说 Mtproto 代理 是 TLS 可用对吗？
