### ISSUE TITLE
请问用大佬的一键脚本安装的GOST解密，对应WIN版本的加密流量转发命令是什么？

### ISSUE THREAD

**Issue by kqs42** [KANIKIG/Multi-EasyGost#41]
小白若用WINDOWS系统做加密隧道流量转发，假设加密方式为ws，请问对应的CMD参数是什么？

**Comment by kqs42** [comment]
小白若用WINDOWS系统做加密隧道流量转发，假设加密方式为ws，用官方的Windows版本，请问对应的CMD参数是什么？

**Comment by KANIKIG** [comment]
不支持ein

**Comment by KANIKIG** [comment]
你好，不支持win
