### ISSUE TITLE
gost 升级到v2.11.3版本后，ws 隧道中转失效

### ISSUE THREAD

**Issue by AndersonGhost** [KANIKIG/Multi-EasyGost#43]
如题所述，将gost升级到最新版本v2.11.3后，发现通过ws隧道中转的节点都失效了。而通过普通tcp+udp中转的都正常。

将ws隧道改为tcp+udp中转后，也都恢复正常。

系统版本为Debian 11.

**Comment by KANIKIG** [comment]
中转和落地两个机器版本都升级，并全部删除，重新设置隧道试试

**Comment by AndersonGhost** [comment]
是呀，两边都升级了，还都重新创建，还是失效。

**Comment by h88782481** [comment]
我也发生了这个问题，不知道为什么

**Comment by mohlee** [comment]
试了很多台vps，v2.11.3 似乎都不能正常工作，无论是tls还是ws都不行，使用不加密中转可以
从未升级新版的机器上拷贝v2.11.1版本 /usr/bin/gost 文件覆盖掉装有 v2.11.3 机器上的相应文件，无论tls和ws都可以正常工作

失效的朋友可以先回退到老版本试试

**Comment by KANIKIG** [comment]
我这边晚点更改下脚本的镜像源，以后2.x的版本就不跟随官方更新了

**Comment by meiti789789** [comment]
我也是今天升级到新版本，跟大家问题一样，所有的隧道都废了，也没有找到旧版本在哪

**Comment by meiti789789** [comment]
> 我这边晚点更改下脚本的镜像源，以后2.x的版本就不跟随官方更新了

在线等，我所有节点 全废了，旧版的在哪里呢

**Comment by meiti789789** [comment]
> 我这边晚点更改下脚本的镜像源，以后2.x的版本就不跟随官方更新了

如何下载v2.11.2版本的gost.sh

**Comment by meiti789789** [comment]
> 从未升级新版的机器上拷贝v2.11.2版本 /usr/bin/gost 文件覆盖掉装有 v2.11.3 机器上的相应文件，无论tls和ws都可以正常工作

能否给一下旧版本的文件

**Comment by KANIKIG** [comment]
已解决

**Comment by meiti789789** [comment]
> 已解决
非常感谢，已更新BUG
