### ISSUE TITLE
无法添加规则

### ISSUE THREAD

**Issue by github-office** [KANIKIG/Multi-EasyGost#48]
国内机器，用国内节点安装，添加规则又以下提示：

awk: fatal: cannot open file `/etc/gost/rawconf' for reading (没有那个文件或目录)
./gost.sh:行788: ((: i <= : 语法错误: 期待操作数 （错误符号是 "<= "）

各位大神，双栈VPS，能监听V4的一个端口转发倒V6地址的端口嘛？

**Comment by KANIKIG** [comment]
脚本没问题，自己检查网络

**Comment by xxhjkl** [comment]
> 脚本没问题，自己检查网络

awk: cannot open /etc/gost/rawconf (No such file or directory)
./gost.sh: line 788: ((: i <= : syntax error: operand expected (error token is "<= ")
同样的错误，国外机器上跑的，应该不是网络问题了吧。看起来是缺了rawconf这个文件。
