### ISSUE TITLE
gost运行时间长了出现断流 重启gost才恢复

### ISSUE THREAD

**Issue by pinssrr** [KANIKIG/Multi-EasyGost#6]
gost运行时间长了出现断流 重启gost才恢复，有望大佬修复一下 我看了GOST群 很多人都出现这个问题了

**Comment by KANIKIG** [comment]
请先自己写crontab定时重启，后续会考虑增加一键设置定时重启。
断流可能是gost本身问题，或者机器的问题，此脚本只是操作gost配置文件。

**Comment by pinssrr** [comment]
ok
