### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by selfmakeit** [KANIKIG/Multi-EasyGost#61]
若为国内机器建议使用大陆镜像加速下载
是否使用？[y/n]:y
--2023-03-29 11:40:50--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/gost-linux-amd64-2.11.2.gz
正在解析主机 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.83
正在连接 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.83|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2023-03-29 11:40:50 错误 403：Forbidden。

gzip: gost-linux-amd64-2.11.2.gz: No such file or directory
mv: 无法获取"gost-linux-amd64-2.11.2" 的文件状态(stat): 没有那个文件或目录
mv: 无法获取"gost" 的文件状态(stat): 没有那个文件或目录
chmod: 无法访问"/usr/bin/gost": 没有那个文件或目录
--2023-03-29 11:40:50--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/gost.service
正在解析主机 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.83
正在连接 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.83|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2023-03-29 11:40:50 错误 403：Forbidden。

--2023-03-29 11:40:50--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/config.json
正在解析主机 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.83
正在连接 gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.83|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2023-03-29 11:40:50 错误 403：Forbidden。

Failed to execute operation: No such file or directory
------------------------------
gost没有安装成功

**Comment by KANIKIG** [comment]
不提供国内下载了
