### ISSUE TITLE
UDP转发日志过多炸盘

### ISSUE THREAD

**Issue by 110560** [KANIKIG/Multi-EasyGost#62]
端口转发tcp+UDP 转发
  Vless的  kcp 协议 日志写入就开始了   可复现， 硬盘占用蹭蹭蹭向上涨  Debian10 11都试了

**Comment by 110560** [comment]
一个小时 写入差不多1GB 日志.... 人麻了 系统是干净的就装了，这个转发

**Comment by laocuiGitHub** [comment]
有日志系统吗？没注意到。

**Comment by laocuiGitHub** [comment]
这个没有日志系统，你说的日志系统是其他系统的吧。

**Comment by 110560** [comment]
> 这个没有日志系统，你说的日志系统是其他系统的吧。

你可以试试 我跑下来是被炸盘了 Debian10/11 系统下转发 vless +kcp 协议

**Comment by 110560** [comment]
![image](https://github.com/KANIKIG/Multi-EasyGost/assets/32481672/5b11e2d2-fde3-4c8d-8424-85e89cf6ad30)
就这个文件

**Comment by 110560** [comment]
![image](https://github.com/KANIKIG/Multi-EasyGost/assets/32481672/dde5d504-9b74-40e8-89f1-319299227e5e)
 打开文件 一堆这个玩意  人没了

**Comment by 110560** [comment]
系统是Debian10

**Comment by 110560** [comment]
@KANIKIG 严重的问题

**Comment by laocuiGitHub** [comment]
我ubuntu18.4没碰到这个问题，我也不清楚了。

**Comment by laocuiGitHub** [comment]
还有我去查了一下这个日志文件，你这个日志属于系统日志覆盖面积很广，不属于单单gost的日志，如果很困扰你的话可以去百度一下，网上有对应的解决办法希望可以帮到你。

**Comment by laocuiGitHub** [comment]
![image](https://github.com/KANIKIG/Multi-EasyGost/assets/99903419/e6203a2e-04a1-4561-a7e6-a7567992b203)
