### ISSUE TITLE
国内服务器的镜像安装不成功

### ISSUE THREAD

**Issue by evsong** [KANIKIG/Multi-EasyGost#65]
是否使用？[y/n]:y
--2023-06-04 18:14:30--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/gost-linux-amd64-2.11.2.gz
Resolving gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.181
Connecting to gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.181|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-06-04 18:14:30 ERROR 403: Forbidden.

gzip: gost-linux-amd64-2.11.2.gz: No such file or directory
mv: cannot stat ‘gost-linux-amd64-2.11.2’: No such file or directory
mv: cannot stat ‘gost’: No such file or directory
chmod: cannot access ‘/usr/bin/gost’: No such file or directory
--2023-06-04 18:14:30--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/gost.service
Resolving gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.181
Connecting to gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.181|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-06-04 18:14:30 ERROR 403: Forbidden.

--2023-06-04 18:14:30--  https://gotunnel.oss-cn-shenzhen.aliyuncs.com/config.json
Resolving gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)... 120.77.166.181
Connecting to gotunnel.oss-cn-shenzhen.aliyuncs.com (gotunnel.oss-cn-shenzhen.aliyuncs.com)|120.77.166.181|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-06-04 18:14:30 ERROR 403: Forbidden.

Failed to execute operation: No such file or directory
------------------------------
gost没有安装成功

是服务器已经失效了嘛？

**Comment by laocuiGitHub** [comment]
国内镜像服务器被恶意流量消耗，暂停提供加速服务了，只能使用国外的镜像源了。
