### ISSUE TITLE
如何使用gost中转Hysteria 2协议？

### ISSUE THREAD

**Issue by AndersonGhost** [KANIKIG/Multi-EasyGost#67]
请教一下大佬，如何使用gost来中转最新的Hysteria 2 协议？感谢~

**Comment by qfomg** [comment]
同问，希望能使用这个功能。

感谢作者，这个一键脚本非常好用。

**Comment by qfomg** [comment]
如何实现gost隧道+加密解密hy2，试了目前的脚本几次都没有成功。
